version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT}:80"
            - "${NGINX_PORT_SSL}:443"
        volumes:
            - ../:/var/www/
            # конфигурация nginx
            - ./config/nginx/:/etc/nginx/conf.d/
            # логи
            - ./logs/nginx:/var/log/nginx/
        networks:
            - web-network

    php8.2:
        build:
            context: .
        container_name: php8.2
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ../:/var/www/
        networks:
            - web-network

    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            # логи
            - ./logs/mysql/:/var/log/mysql
            # храним базу локально
            - ./database/mysql:/var/lib/mysql
        security_opt:
            - seccomp:unconfined
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - web-network

networks:
    web-network:
        driver: bridge
